server:
  port: 15000

spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: update
    show-sql: false

  datasource:
    url: jdbc:postgresql://dpg-chjikvqk728k56jrms30-a.frankfurt-postgres.render.com/dbsonar?user=dbsonar_user&password=S7LBXV9QsASiD1N5p1lLekoUgSpYpMgv
    username: dbsonar_user
    password: S7LBXV9QsASiD1N5p1lLekoUgSpYpMgv
    driver-class-name: org.postgresql.Driver

