server:
  port: 15000

spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false

  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://postgres:5432/postgres}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

logging:
  level:
    org:
      springframework:
        security: TRACE

springdoc:
  swagger-ui:
    path:
      "/"

