server:
  port: 15000

spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: update
    show-sql: false

  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:15001/postgres}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

