version: "3.9"

services:
  midpoint_sonar:
    build: .
    ports:
      - "15000:15000"

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "15001:5432"
